const uri = 'https://ik.imagekit.io/wnvkyjz511xn/products'
const products = [
  {
    id: 1,
    name: 'vintage typewriter',
    image: `${uri}/p1.png`,

    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 2,
    name: 'Shoes',
    image: `${uri}/shoe.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 3,
    name: 'Tea Cup',
    image: `${uri}/tea-cup.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 4,
    name: 'Ear Bud',
    image: `${uri}/ear-bud.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 5,
    name: 'Ring',
    image: `${uri}/ring.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 6,
    name: 'Nail pollish',
    image: `${uri}/nail_polish.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 7,
    name: 'purse',
    image: `${uri}/purse.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
  {
    id: 8,
    name: 'power  bank',
    image: `${uri}/powerbank.png`,
    description: 'Lorem ipsum dolor sit amet consectetur.',
    rate: 4,
    amount: 2000,
    deduct: 600,
    seller: 'Hullon Official Store',
  },
]

export default products
